all:
	g++ -g -I/home/hdhzero/app/mesa/mesa-12.0.0/binaries/include `pkg-config --cflags gtk+-3.0` -o scad scad.cpp ScadMainWindow.cpp SchematicGui.cpp DrawingArea.cpp `pkg-config --libs gtk+-3.0` -L/home/hdhzero/app/mesa/mesa-12.0.0/binaries/lib -lGL -lGLEW

